### ISSUE TITLE
Error: Template without a view

### ISSUE THREAD

**Issue by lorensr** [aldeed/meteor-template-extension#28] opened 2015-03-22 23:50 UTC
When I add this package, `v3.4.3`, I get this error:

```
Exception in template helper: TypeError: Cannot read property 'name' of undefined
    at runTemplateHooks (http://localhost:3000/packages/aldeed_template-extension.js?2e25a48119980b3ff2fba34bcf67b18deac45199:412:72)
    at Object.templateExtensionMasterHook (http://localhost:3000/packages/aldeed_template-extension.js?2e25a48119980b3ff2fba34bcf67b18deac45199:364:5)
    at bindDataContext (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2786:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:1607:16)
    at http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2834:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:3382:12)
    at wrapHelper (http://localhost:3000/packages/blaze.js?4e49999979a58da0e2265f7bd3f5910f9901b07b:2833:27)
    at Spacebars.call (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:169:51)
    at Spacebars.mustacheImpl (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:109:25)
    at Object.Spacebars.mustache (http://localhost:3000/packages/spacebars.js?7bafbe05ec09b6bbb6a3b276537e4995ab298a2f:113:39)
```

```
                              // 370
function runTemplateHooks(type, template, args) {                                                                   // 371
  var i, name = parseName(template.viewName) || parseName(template.view.name), h = templateHooks[type][name];       // 372
```

I guess that means one of my templates doesn't have a view? I can't imagine why.

**Comment by aldeed** [comment] 2015-03-23 01:02
Not sure. Is this with Meteor 1.0.4+? We haven't tested and updated for the new Meteor release yet.

**Comment by lorensr** [comment] 2015-03-23 01:14
yep, 
```
$ m --version
Meteor 1.0.4.2
```

**Comment by aldeed** [comment] 2015-03-26 13:15
@lorensr, I looked into this a bit and I can't reproduce, and all tests are passing with Meteor 1.0.4+. Can you link to a repo with a simple reproduction so we can figure out what's happening?

We do still need to update this pkg to play more nicely with the new onCreated/onRendered/onDestroyed, but I'm not sure if that's related to your issue.

**Comment by lorensr** [comment] 2015-03-26 19:46
I can't reproduce, it's a large app, and I'm just adding the package, not calling anything. Looks like it would be fixed by checking if view is undefined before accessing the name

**Comment by lorensr** [comment] 2015-04-15 11:02
Maybe something like this?
```js
var i, name = parseName(template.viewName);
if (!name) {
  if (template.view) {
    name = parseName(template.view.name);
  } else {
    return;
  }
}
var h = templateHooks[type][name];  
```

**Comment by voidale** [comment] 2015-04-21 08:32
@aldeed  I get the same error I can reproduce it easily just try to invoke rendered  `Template.Name.rendered()` in console. It will not work.

**Comment by lorensr** [comment] 2015-04-21 08:48
That error occurs elsewhere in the package, but it does come from the same problem of `template.view` being `undefined`:

![image](https://cloud.githubusercontent.com/assets/251288/7248554/84049de8-e7c8-11e4-80b0-941ef8db343f.png)

**Comment by MasterAM** [comment] 2015-05-17 08:32
This happened to me when I was trying to send a data property called `created` as an argument to a template helper:

```handlebars
<span class="date">{{datetime created}}</span>
```

It then tried to run the template hooks, but got the data object instead of the template instance.

Changing the property name or removing the parameter resolves this.

**Comment by lorensr** [comment] 2015-05-17 09:12
Wow. Thank you!!! Fixed it.

Before: `{{days_ago created}}`

After:
```
{{days_ago get_created}}
```
```
UI.registerHelper 'get_created', ->
  @created
```

**Comment by aldeed** [comment] 2017-03-03 14:00
Closing. Pretty sure this was fixed awhile back.

**Closed by aldeed** 2017-03-03 14:00 UTC
Labels: potential bug
